name: Jekyll site CI

on: [deployment]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: create deployment
      run: |
        echo "this buiid is done"
